version: '3.9'
services:
  api-gateway:
    container_name: api-gateway
    build: 
      context: ./api-gateway
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    networks:
      - projects-handler
      - gateway-network
    env_file:
      - ./api-gateway/.env
    depends_on:
      - projects-ms
      - tasks-ms
      - redis-gateway
    volumes:
      - ./api-gateway:/var/www/html/projects-handler/api-gateway
      - /var/www/html/projects-handler/api-gateway/node_modules

  redis-gateway:
    container_name: redis-gateway
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - gateway-network
    volumes:
      - data-redis-dev:/data

  projects-ms:
    container_name: projects-ms
    build: 
      context: ./projects-ms
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    env_file:
      - ./projects-ms/.env
    volumes:
      - ./projects-ms:/var/www/html/projects-handler/projects-ms
      - /var/www/html/projects-handler/projects-ms/node_modules
    depends_on:
      - postgres-projects
    networks:
      - project-ms-network
      - projects-handler

  postgres-projects:
    image: postgres:17
    container_name: postgres-projects
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=pjmroot
      - POSTGRES_PASSWORD=toormjp
      - POSTGRES_DB=projectsdb
    volumes:
      - data-postgres-dev:/var/lib/postgresql/data
    networks:
      - project-ms-network

  tasks-ms:
    container_name: tasks-ms
    build: 
      context: ./tasks-ms
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3002"
    env_file:
      - ./tasks-ms/.env
    volumes:
      - ./tasks-ms:/var/www/html/tasks-handler/tasks-ms
      - /var/www/html/tasks-handler/tasks-ms/node_modules
    depends_on:
      - mongo-tasks
    networks:
      - task-ms-network
      - projects-handler

  mongo-tasks:
    image: mongo:7
    container_name: mongo-tasks
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: tsmroot 
      MONGO_INITDB_ROOT_PASSWORD: toormst
    volumes:
      - data-mondo-dev:/data/db
      - ./tasks-ms/src/resources/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    networks:
      - task-ms-network

networks:
  projects-handler:
    driver: bridge
    name: projects-handler
  project-ms-network:
    driver: bridge
    name: project-ms-network
  task-ms-network:
    driver: bridge
    name: task-ms-network
  gateway-network:
    driver: bridge
    name: gateway-network

volumes:
  data-postgres-dev:
  data-mondo-dev:
  data-redis-dev:
