version: "3.9"
services:
  mongo_tasks:
    container_name: mongo_tasks
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123456
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: