FROM node:22

RUN npm i -g pnpm

RUN mkdir -p /var/www/html/projects-handler/tasks-ms

WORKDIR /var/www/html/projects-handler/tasks-ms

COPY package*.json .

RUN pnpm install

COPY . .

EXPOSE 3002

CMD ["pnpm", "run", "start:dev"]