FROM node:18

RUN npm i -g pnpm

RUN mkdir -p /var/www/html/projects-handler/users-ms

WORKDIR /var/www/html/projects-handler/users-ms

COPY package*.json .

RUN pnpm install

COPY . .

EXPOSE 3000

CMD ["pnpm", "run", "start:dev"]