version: '3.9'
services:
  projects-ms:
    container_name: projects-ms
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:${PORT}"
    env_file:
      - .env
    volumes:
      - .:/var/www/html/projects-ms
      - /var/www/html/projects-ms/node_modules
    depends_on:
      - mongo-projects
    networks:
      - project-ms-network
      - projects-handler

  mongo-projects:
    image: mongo:6
    container_name: mongo-projects
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=pjmroot
      - MONGO_INITDB_ROOT_PASSWORD=toormjp
    volumes:
      - ./src/prisma/db/init-projects-mongo.js:/docker-entrypoint-initdb.d/init-projects-mongo.js
      - data-mongo-dev:/data/db
    networks:
      - project-ms-network

networks:
  project-ms-network:
    driver: bridge
volumes:
  data-mongo-dev:
