FROM node:22

RUN npm i -g pnpm

RUN mkdir -p /var/www/html/projects-ms

WORKDIR /var/www/html/projects-ms

COPY package*.json .

RUN pnpm install

COPY . .

RUN npx prisma generate

EXPOSE 3000

CMD ["pnpm", "run", "start:dev"]