FROM node:22

RUN npm i -g pnpm

RUN mkdir -p /var/www/html/projects-handler/projects-ms

WORKDIR /var/www/html/projects-handler/projects-ms

COPY package*.json .

RUN pnpm install

COPY . .

RUN npx prisma generate

COPY start.sh /usr/local/bin/start.sh
RUN chmod +x /usr/local/bin/start.sh

EXPOSE 3001

CMD ["sh", "/usr/local/bin/start.sh"]